// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Macros.Item;
using Soenneker.Intercom.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Intercom.OpenApiClient.Macros
{
    /// <summary>
    /// Builds and executes requests for operations under \macros
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MacrosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Intercom.OpenApiClient.macros.item collection</summary>
        /// <param name="position">The unique identifier of the macro</param>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Macros.Item.MacrosItemRequestBuilder"/></returns>
        public global::Soenneker.Intercom.OpenApiClient.Macros.Item.MacrosItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Intercom.OpenApiClient.Macros.Item.MacrosItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MacrosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/macros{?per_page*,starting_after*,updated_since*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MacrosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/macros{?per_page*,starting_after*,updated_since*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;You can fetch a list of all macros (saved replies) in your workspace for use in automating responses.The macros are returned in descending order by updated_at.**Pagination**This endpoint uses cursor-based pagination via the `starting_after` parameter. The cursor is a Base64-encoded JSON array containing `[updated_at, id]` of the last item from the previous page.**Placeholder Transformation**The API transforms Intercom placeholders to a more standard XML-like format:- From: `{{user.name | fallback: &apos;there&apos;}}`- To: `&lt;attribute key=\&quot;user.name\&quot; default=\&quot;there\&quot;/&gt;`&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.MacroList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Intercom.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Intercom.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Intercom.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Intercom.OpenApiClient.Models.MacroList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder.MacrosRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Intercom.OpenApiClient.Models.MacroList> GetAsync(Action<RequestConfiguration<global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder.MacrosRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Intercom.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Intercom.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Intercom.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Intercom.OpenApiClient.Models.MacroList>(requestInfo, global::Soenneker.Intercom.OpenApiClient.Models.MacroList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;You can fetch a list of all macros (saved replies) in your workspace for use in automating responses.The macros are returned in descending order by updated_at.**Pagination**This endpoint uses cursor-based pagination via the `starting_after` parameter. The cursor is a Base64-encoded JSON array containing `[updated_at, id]` of the last item from the previous page.**Placeholder Transformation**The API transforms Intercom placeholders to a more standard XML-like format:- From: `{{user.name | fallback: &apos;there&apos;}}`- To: `&lt;attribute key=\&quot;user.name\&quot; default=\&quot;there\&quot;/&gt;`&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder.MacrosRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder.MacrosRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Intercom.OpenApiClient.Macros.MacrosRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;You can fetch a list of all macros (saved replies) in your workspace for use in automating responses.The macros are returned in descending order by updated_at.**Pagination**This endpoint uses cursor-based pagination via the `starting_after` parameter. The cursor is a Base64-encoded JSON array containing `[updated_at, id]` of the last item from the previous page.**Placeholder Transformation**The API transforms Intercom placeholders to a more standard XML-like format:- From: `{{user.name | fallback: &apos;there&apos;}}`- To: `&lt;attribute key=\&quot;user.name\&quot; default=\&quot;there\&quot;/&gt;`&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MacrosRequestBuilderGetQueryParameters 
        {
            /// <summary>The number of results per page</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>Base64-encoded cursor containing [updated_at, id] for pagination</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("starting_after")]
            public string? StartingAfter { get; set; }
#nullable restore
#else
            [QueryParameter("starting_after")]
            public string StartingAfter { get; set; }
#endif
            /// <summary>Unix timestamp to filter macros updated after this time</summary>
            [QueryParameter("updated_since")]
            public long? UpdatedSince { get; set; }
        }
    }
}
#pragma warning restore CS0618
