// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Export.Cancel.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.Export.Cancel
{
    /// <summary>
    /// Builds and executes requests for operations under \export\cancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Intercom.OpenApiClient.export.cancel.item collection</summary>
        /// <param name="position">job_identifier</param>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Export.Cancel.Item.WithJob_identifierItemRequestBuilder"/></returns>
        public global::Soenneker.Intercom.OpenApiClient.Export.Cancel.Item.WithJob_identifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("job_identifier", position);
                return new global::Soenneker.Intercom.OpenApiClient.Export.Cancel.Item.WithJob_identifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Export.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/export/cancel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Export.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/export/cancel", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
