// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.News.News_items;
using Soenneker.Intercom.OpenApiClient.News.Newsfeeds;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.News
{
    /// <summary>
    /// Builds and executes requests for operations under \news
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The news_items property</summary>
        public global::Soenneker.Intercom.OpenApiClient.News.News_items.News_itemsRequestBuilder News_items
        {
            get => new global::Soenneker.Intercom.OpenApiClient.News.News_items.News_itemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The newsfeeds property</summary>
        public global::Soenneker.Intercom.OpenApiClient.News.Newsfeeds.NewsfeedsRequestBuilder Newsfeeds
        {
            get => new global::Soenneker.Intercom.OpenApiClient.News.Newsfeeds.NewsfeedsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.News.NewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/news", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.News.NewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/news", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
