// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.Fin_voice.External_id
{
    /// <summary>
    /// Builds and executes requests for operations under \fin_voice\external_id
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class External_idRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Intercom.OpenApiClient.fin_voice.external_id.item collection</summary>
        /// <param name="position">The external call identifier from the call provider</param>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.Item.WithExternal_ItemRequestBuilder"/></returns>
        public global::Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.Item.WithExternal_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("external_id", position);
                return new global::Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.Item.WithExternal_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.External_idRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public External_idRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fin_voice/external_id", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Fin_voice.External_id.External_idRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public External_idRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fin_voice/external_id", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
