// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Contacts.Bulk.Item;
using Soenneker.Intercom.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Intercom.OpenApiClient.Contacts.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts\bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Intercom.OpenApiClient.contacts.bulk.item collection</summary>
        /// <param name="position">The unique identifier for the bulk job.</param>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.Item.BulkItemRequestBuilder"/></returns>
        public global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.Item.BulkItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.Item.BulkItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts/bulk", rawUrl)
        {
        }
        /// <summary>
        /// You can bulk update contacts by submitting an array of contact objects with the fields to update. Each contact must include an `id` field identifying the contact to update.The endpoint creates an async job that processes the updates in the background. Use the returned job ID with `GET /contacts/bulk/{id}` to check the job status.{% admonition type=&quot;info&quot; name=&quot;Limits&quot; %}  - Maximum of 100 contacts per request.  - You can append tasks to an existing job by including `job.id` in the request body.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ContactsBulkJob"/></returns>
        /// <param name="body">Request body for bulk updating contacts.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Intercom.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Intercom.OpenApiClient.Models.Error">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Intercom.OpenApiClient.Models.ContactsBulkJob?> PostAsync(global::Soenneker.Intercom.OpenApiClient.Models.BulkUpdateContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Intercom.OpenApiClient.Models.ContactsBulkJob> PostAsync(global::Soenneker.Intercom.OpenApiClient.Models.BulkUpdateContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Intercom.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Intercom.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Intercom.OpenApiClient.Models.ContactsBulkJob>(requestInfo, global::Soenneker.Intercom.OpenApiClient.Models.ContactsBulkJob.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// You can bulk update contacts by submitting an array of contact objects with the fields to update. Each contact must include an `id` field identifying the contact to update.The endpoint creates an async job that processes the updates in the background. Use the returned job ID with `GET /contacts/bulk/{id}` to check the job status.{% admonition type=&quot;info&quot; name=&quot;Limits&quot; %}  - Maximum of 100 contacts per request.  - You can append tasks to an existing job by including `job.id` in the request body.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for bulk updating contacts.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Intercom.OpenApiClient.Models.BulkUpdateContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Intercom.OpenApiClient.Models.BulkUpdateContactsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.BulkRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.BulkRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Intercom.OpenApiClient.Contacts.Bulk.BulkRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
