// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Download.Content;
using Soenneker.Intercom.OpenApiClient.Download.Reporting_data;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The content property</summary>
        public global::Soenneker.Intercom.OpenApiClient.Download.Content.ContentRequestBuilder Content
        {
            get => new global::Soenneker.Intercom.OpenApiClient.Download.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reporting_data property</summary>
        public global::Soenneker.Intercom.OpenApiClient.Download.Reporting_data.Reporting_dataRequestBuilder Reporting_data
        {
            get => new global::Soenneker.Intercom.OpenApiClient.Download.Reporting_data.Reporting_dataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/download", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
