// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Procedures.Item.Collect_agent_input;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.Procedures.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \procedures\{conversation_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConversation_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collect_agent_input property</summary>
        public global::Soenneker.Intercom.OpenApiClient.Procedures.Item.Collect_agent_input.Collect_agent_inputRequestBuilder Collect_agent_input
        {
            get => new global::Soenneker.Intercom.OpenApiClient.Procedures.Item.Collect_agent_input.Collect_agent_inputRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Procedures.Item.WithConversation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversation_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/procedures/{conversation_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Procedures.Item.WithConversation_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversation_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/procedures/{conversation_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
