// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item.Run;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \fin\procedures\{procedureId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProcedureItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The run property</summary>
        public global::Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item.Run.RunRequestBuilder Run
        {
            get => new global::Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item.WithProcedureItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProcedureItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fin/procedures/{procedureId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Fin.Procedures.Item.WithProcedureItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProcedureItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fin/procedures/{procedureId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
