// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// Additional data provided about Admin activity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityLogMetadata : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates the state was derived automatically rather than set by an Admin.</summary>
        public bool? Auto { get; set; }
        /// <summary>Indicates if the status was changed automatically or manually.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoChanged { get; set; }
#nullable restore
#else
        public string AutoChanged { get; set; }
#endif
        /// <summary>The away mode status which is set to true when away and false when returned.</summary>
        public bool? AwayMode { get; set; }
        /// <summary>The reason the Admin is away.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AwayStatusReason { get; set; }
#nullable restore
#else
        public string AwayStatusReason { get; set; }
#endif
        /// <summary>The settings altered by the change, keyed by setting name. Only settings whose value actually moved are included, so an unchanged setting is absent rather than present with equal values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadataChangesProperty? Changes { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadataChangesProperty Changes { get; set; }
#endif
        /// <summary>The conversation assignment limit value for an admin.</summary>
        public int? ConversationAssignmentLimit { get; set; }
        /// <summary>The unique identifier for the contact which is provided by the Client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The time of the Admin&apos;s last recorded activity.</summary>
        public int? LastActivityAt { get; set; }
        /// <summary>The state after the change. `idle` or `occupied`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewState { get; set; }
#nullable restore
#else
        public string NewState { get; set; }
#endif
        /// <summary>The state before the change. `idle` or `occupied`, and null when the Admin had not been classified yet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousState { get; set; }
#nullable restore
#else
        public string PreviousState { get; set; }
#endif
        /// <summary>Indicates if conversations should be reassigned while an Admin is away.</summary>
        public bool? ReassignConversations { get; set; }
        /// <summary>The group of workspace settings the change belongs to, for example `teammate_occupancy` or `automatic_away_mode`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SettingType { get; set; }
#nullable restore
#else
        public string SettingType { get; set; }
#endif
        /// <summary>The way the admin signed in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignInMethod { get; set; }
#nullable restore
#else
        public string SignInMethod { get; set; }
#endif
        /// <summary>The action that initiated the status change.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The inactivity window, in minutes, used to classify the Admin.</summary>
        public int? ThresholdMinutes { get; set; }
        /// <summary>The ticket assignment limit value for an admin.</summary>
        public int? TicketAssignmentLimit { get; set; }
        /// <summary>The ID of the Admin who initiated the activity.</summary>
        public int? UpdateBy { get; set; }
        /// <summary>The name of the Admin who initiated the activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateByName { get; set; }
#nullable restore
#else
        public string UpdateByName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadata"/> and sets the default values.
        /// </summary>
        public ActivityLogMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto", n => { Auto = n.GetBoolValue(); } },
                { "auto_changed", n => { AutoChanged = n.GetStringValue(); } },
                { "away_mode", n => { AwayMode = n.GetBoolValue(); } },
                { "away_status_reason", n => { AwayStatusReason = n.GetStringValue(); } },
                { "changes", n => { Changes = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadataChangesProperty>(global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadataChangesProperty.CreateFromDiscriminatorValue); } },
                { "conversation_assignment_limit", n => { ConversationAssignmentLimit = n.GetIntValue(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "last_activity_at", n => { LastActivityAt = n.GetIntValue(); } },
                { "new_state", n => { NewState = n.GetStringValue(); } },
                { "previous_state", n => { PreviousState = n.GetStringValue(); } },
                { "reassign_conversations", n => { ReassignConversations = n.GetBoolValue(); } },
                { "setting_type", n => { SettingType = n.GetStringValue(); } },
                { "sign_in_method", n => { SignInMethod = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "threshold_minutes", n => { ThresholdMinutes = n.GetIntValue(); } },
                { "ticket_assignment_limit", n => { TicketAssignmentLimit = n.GetIntValue(); } },
                { "update_by", n => { UpdateBy = n.GetIntValue(); } },
                { "update_by_name", n => { UpdateByName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("auto", Auto);
            writer.WriteStringValue("auto_changed", AutoChanged);
            writer.WriteBoolValue("away_mode", AwayMode);
            writer.WriteStringValue("away_status_reason", AwayStatusReason);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.ActivityLogMetadataChangesProperty>("changes", Changes);
            writer.WriteIntValue("conversation_assignment_limit", ConversationAssignmentLimit);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteIntValue("last_activity_at", LastActivityAt);
            writer.WriteStringValue("new_state", NewState);
            writer.WriteStringValue("previous_state", PreviousState);
            writer.WriteBoolValue("reassign_conversations", ReassignConversations);
            writer.WriteStringValue("setting_type", SettingType);
            writer.WriteStringValue("sign_in_method", SignInMethod);
            writer.WriteStringValue("source", Source);
            writer.WriteIntValue("threshold_minutes", ThresholdMinutes);
            writer.WriteIntValue("ticket_assignment_limit", TicketAssignmentLimit);
            writer.WriteIntValue("update_by", UpdateBy);
            writer.WriteStringValue("update_by_name", UpdateByName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
