// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// A historical version of an article, including its content.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArticleVersion : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the article this version belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArticleId { get; set; }
#nullable restore
#else
        public string ArticleId { get; set; }
#endif
        /// <summary>The id of the teammate listed as the article&apos;s author at this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorId { get; set; }
#nullable restore
#else
        public string AuthorId { get; set; }
#endif
        /// <summary>The HTML body of the article at this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The Markdown body of the article at this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyMarkdown { get; set; }
#nullable restore
#else
        public string BodyMarkdown { get; set; }
#endif
        /// <summary>The time the version was created, as a UTC Unix timestamp.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The id of the teammate who created this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedById { get; set; }
#nullable restore
#else
        public string CreatedById { get; set; }
#endif
        /// <summary>How this version was created (for example `web`, `api`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedVia { get; set; }
#nullable restore
#else
        public string CreatedVia { get; set; }
#endif
        /// <summary>The description of the article at this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id of the version this version was created from, or `null` if this is the first version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromVersionId { get; set; }
#nullable restore
#else
        public string FromVersionId { get; set; }
#endif
        /// <summary>The unique identifier for the version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this version is the currently published version of the article (`published`) or an earlier non-live version (`draft`).</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionState? State { get; set; }
        /// <summary>The title of the article at this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>String representing the object&apos;s type. Always has the value `article_version`.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionType? Type { get; set; }
        /// <summary>The time the version was last updated, as a UTC Unix timestamp.</summary>
        public int? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersion"/> and sets the default values.
        /// </summary>
        public ArticleVersion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "article_id", n => { ArticleId = n.GetStringValue(); } },
                { "author_id", n => { AuthorId = n.GetStringValue(); } },
                { "body", n => { Body = n.GetStringValue(); } },
                { "body_markdown", n => { BodyMarkdown = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "created_by_id", n => { CreatedById = n.GetStringValue(); } },
                { "created_via", n => { CreatedVia = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "from_version_id", n => { FromVersionId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionState>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("article_id", ArticleId);
            writer.WriteStringValue("author_id", AuthorId);
            writer.WriteStringValue("body", Body);
            writer.WriteStringValue("body_markdown", BodyMarkdown);
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteStringValue("created_by_id", CreatedById);
            writer.WriteStringValue("created_via", CreatedVia);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("from_version_id", FromVersionId);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionState>("state", State);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ArticleVersionType>("type", Type);
            writer.WriteIntValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
