// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>String representing the object&apos;s type. Always has the value `article_version`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ArticleVersionType
    {
        [EnumMember(Value = "article_version")]
        #pragma warning disable CS1591
        ArticleVersion,
        #pragma warning restore CS1591
    }
}
