// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// Required when `action` is `set_availability`. Each field is optional — only theproperties present in the request are toggled.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContentBulkActionRequestAvailability : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Toggle Fin AI Agent availability.</summary>
        public bool? AiAgent { get; set; }
        /// <summary>Toggle Copilot availability.</summary>
        public bool? Copilot { get; set; }
        /// <summary>Toggle Sales Agent availability.</summary>
        public bool? SalesAgent { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ContentBulkActionRequestAvailability"/> and sets the default values.
        /// </summary>
        public ContentBulkActionRequestAvailability()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ContentBulkActionRequestAvailability"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.ContentBulkActionRequestAvailability CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.ContentBulkActionRequestAvailability();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ai_agent", n => { AiAgent = n.GetBoolValue(); } },
                { "copilot", n => { Copilot = n.GetBoolValue(); } },
                { "sales_agent", n => { SalesAgent = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ai_agent", AiAgent);
            writer.WriteBoolValue("copilot", Copilot);
            writer.WriteBoolValue("sales_agent", SalesAgent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
