// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The order to sort the results in. Defaults to `descending` when omitted. Values other than `ascending` or `descending` return a `400` error with code `invalid_sort_order`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ContactSearchRequestSortOrder
    {
        [EnumMember(Value = "ascending")]
        #pragma warning disable CS1591
        Ascending,
        #pragma warning restore CS1591
        [EnumMember(Value = "descending")]
        #pragma warning disable CS1591
        Descending,
        #pragma warning restore CS1591
    }
}
