// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// An external source for External Pages that you add to your Fin Content Library.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Content_import_source : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time when the content import source was created.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The unique identifier for the content import source which is given by Intercom.</summary>
        public int? Id { get; set; }
        /// <summary>The time when the content import source was last synced.</summary>
        public int? LastSyncedAt { get; set; }
        /// <summary>The status of the content import source.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_status? Status { get; set; }
        /// <summary>If you intend to create or update External Pages via the API, this should be set to `api`.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_sync_behavior? SyncBehavior { get; set; }
        /// <summary>Always external_page</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_type? Type { get; set; }
        /// <summary>The time when the content import source was last updated.</summary>
        public int? UpdatedAt { get; set; }
        /// <summary>The URL of the root of the external source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source"/> and sets the default values.
        /// </summary>
        public Content_import_source()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_status.Active;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "last_synced_at", n => { LastSyncedAt = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_status>(); } },
                { "sync_behavior", n => { SyncBehavior = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_sync_behavior>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetIntValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("last_synced_at", LastSyncedAt);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_status>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_sync_behavior>("sync_behavior", SyncBehavior);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Content_import_source_type>("type", Type);
            writer.WriteIntValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
