// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The kind of reviser. `ai` if Fin changed the review; `admin` if a teammate did.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConversationScorecardRevisedByType
    {
        [EnumMember(Value = "ai")]
        #pragma warning disable CS1591
        Ai,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
    }
}
