// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConversationPartsType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "conversation_part.list")]
        #pragma warning disable CS1591
        ConversationPartList,
        #pragma warning restore CS1591
    }
}
