// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// A QA monitor evaluation that flagged this conversation. Returned in the `monitor_evaluations` array on conversation responses when `include_monitors=true` is passed.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationMonitorEvaluation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time the monitor evaluated this conversation. Null in the rare case the underlying record&apos;s timestamp is not yet set.</summary>
        public int? EvaluatedAt { get; set; }
        /// <summary>The reasoning provided by the monitor for its result. May be null if no reasoning was generated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Explanation { get; set; }
#nullable restore
#else
        public string Explanation { get; set; }
#endif
        /// <summary>The unique identifier of the monitor that produced this evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonitorId { get; set; }
#nullable restore
#else
        public string MonitorId { get; set; }
#endif
        /// <summary>The name of the monitor at the time of evaluation. Null if the monitor has since been deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonitorName { get; set; }
#nullable restore
#else
        public string MonitorName { get; set; }
#endif
        /// <summary>The type of the monitor. Null if the monitor has since been deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonitorType { get; set; }
#nullable restore
#else
        public string MonitorType { get; set; }
#endif
        /// <summary>The evaluation outcome reported by the monitor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Result { get; set; }
#nullable restore
#else
        public string Result { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ConversationMonitorEvaluation"/> and sets the default values.
        /// </summary>
        public ConversationMonitorEvaluation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.ConversationMonitorEvaluation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.ConversationMonitorEvaluation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.ConversationMonitorEvaluation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "evaluated_at", n => { EvaluatedAt = n.GetIntValue(); } },
                { "explanation", n => { Explanation = n.GetStringValue(); } },
                { "monitor_id", n => { MonitorId = n.GetStringValue(); } },
                { "monitor_name", n => { MonitorName = n.GetStringValue(); } },
                { "monitor_type", n => { MonitorType = n.GetStringValue(); } },
                { "result", n => { Result = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("evaluated_at", EvaluatedAt);
            writer.WriteStringValue("explanation", Explanation);
            writer.WriteStringValue("monitor_id", MonitorId);
            writer.WriteStringValue("monitor_name", MonitorName);
            writer.WriteStringValue("monitor_type", MonitorType);
            writer.WriteStringValue("result", Result);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
