// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>Can be set to &quot;open&quot;, &quot;closed&quot; or &quot;snoozed&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Conversation_list_item_state
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
        [EnumMember(Value = "snoozed")]
        #pragma warning disable CS1591
        Snoozed,
        #pragma warning restore CS1591
    }
}
