// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// The type of the conversation part that started this conversation. Can be Contact, Admin, Campaign, Automated or Operator initiated.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Conversation_source : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of attachments for the part.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Intercom.OpenApiClient.Models.Part_attachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Intercom.OpenApiClient.Models.Part_attachment> Attachments { get; set; }
#endif
        /// <summary>The object who initiated the conversation, which can be a Contact, Admin or Team. Bots and campaigns send messages on behalf of Admins or Teams. For Twitter, this will be blank.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.Conversation_part_author? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.Conversation_part_author Author { get; set; }
#endif
        /// <summary>The message body, which may contain HTML. For Twitter, this will show a generic message regarding why the body is obscured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The conversation&apos;s initiation type. Possible values are customer_initiated, campaigns_initiated (legacy campaigns), operator_initiated (Custom bot), automated (Series and other outbounds with dynamic audience message) and admin_initiated (fixed audience message, ticket initiated by an admin, group email).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveredAs { get; set; }
#nullable restore
#else
        public string DeliveredAs { get; set; }
#endif
        /// <summary>Contains metadata if the message was sent as an email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.Source_email_message_metadata? EmailMessageMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.Source_email_message_metadata EmailMessageMetadata { get; set; }
#endif
        /// <summary>The id representing the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether or not the source message has been redacted. Only applicable for contact initiated messages.</summary>
        public bool? Redacted { get; set; }
        /// <summary>Optional. The message subject. For Twitter, this will show a generic message regarding why the subject is obscured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>This includes conversation, email, facebook, instagram, phone_call, phone_switch, push, sms, twitter and whatsapp.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source_type? Type { get; set; }
        /// <summary>The URL where the conversation was started. For Twitter, Email, and Bots, this will be blank.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source"/> and sets the default values.
        /// </summary>
        public Conversation_source()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.Part_attachment>(global::Soenneker.Intercom.OpenApiClient.Models.Part_attachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.Conversation_part_author>(global::Soenneker.Intercom.OpenApiClient.Models.Conversation_part_author.CreateFromDiscriminatorValue); } },
                { "body", n => { Body = n.GetStringValue(); } },
                { "delivered_as", n => { DeliveredAs = n.GetStringValue(); } },
                { "email_message_metadata", n => { EmailMessageMetadata = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.Source_email_message_metadata>(global::Soenneker.Intercom.OpenApiClient.Models.Source_email_message_metadata.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "redacted", n => { Redacted = n.GetBoolValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source_type>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.Part_attachment>("attachments", Attachments);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.Conversation_part_author>("author", Author);
            writer.WriteStringValue("body", Body);
            writer.WriteStringValue("delivered_as", DeliveredAs);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.Source_email_message_metadata>("email_message_metadata", EmailMessageMetadata);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("redacted", Redacted);
            writer.WriteStringValue("subject", Subject);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Conversation_source_type>("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
