// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>If marked as priority, it will return priority or else not_priority.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Conversation_list_item_priority
    {
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_priority")]
        #pragma warning disable CS1591
        Not_priority,
        #pragma warning restore CS1591
    }
}
