// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute"/>, <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateDataAttributeRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute? CreateDataAttributeRequestListAttribute { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute CreateDataAttributeRequestListAttribute { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType? CreateDataAttributeRequestOtherType { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType CreateDataAttributeRequestOtherType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequest();
            if("CreateDataAttributeRequestListAttribute".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateDataAttributeRequestListAttribute = new global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute();
            }
            else if("CreateDataAttributeRequestOtherType".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateDataAttributeRequestOtherType = new global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateDataAttributeRequestListAttribute != null)
            {
                return CreateDataAttributeRequestListAttribute.GetFieldDeserializers();
            }
            else if(CreateDataAttributeRequestOtherType != null)
            {
                return CreateDataAttributeRequestOtherType.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateDataAttributeRequestListAttribute != null)
            {
                writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestListAttribute>(null, CreateDataAttributeRequestListAttribute);
            }
            else if(CreateDataAttributeRequestOtherType != null)
            {
                writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.CreateDataAttributeRequestOtherType>(null, CreateDataAttributeRequestOtherType);
            }
        }
    }
}
#pragma warning restore CS0618
