// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>&quot;The cardinality of the relationship: `one` or `many`.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateConversationAttributeRelationshipRequestAllOf2ReferenceType
    {
        [EnumMember(Value = "one")]
        #pragma warning disable CS1591
        One,
        #pragma warning restore CS1591
        [EnumMember(Value = "many")]
        #pragma warning disable CS1591
        Many,
        #pragma warning restore CS1591
    }
}
