// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of message that was sent. Can be email, inapp, facebook, twitter, sms or whatsapp.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateConversation200_message_type
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "inapp")]
        #pragma warning disable CS1591
        Inapp,
        #pragma warning restore CS1591
        [EnumMember(Value = "facebook")]
        #pragma warning disable CS1591
        Facebook,
        #pragma warning restore CS1591
        [EnumMember(Value = "twitter")]
        #pragma warning disable CS1591
        Twitter,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
        [EnumMember(Value = "whatsapp")]
        #pragma warning disable CS1591
        Whatsapp,
        #pragma warning restore CS1591
    }
}
