// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2"/>, <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Recipient"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateMessageRequestBcc : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2? CreateMessageRequestBccBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2 CreateMessageRequestBccBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Recipient"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.Recipient? Recipient { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.Recipient Recipient { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBcc"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBcc CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBcc();
            if("CreateMessageRequestBcc_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateMessageRequestBccBranch2 = new global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2();
            }
            else if("Recipient".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Recipient = new global::Soenneker.Intercom.OpenApiClient.Models.Recipient();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateMessageRequestBccBranch2 != null)
            {
                return CreateMessageRequestBccBranch2.GetFieldDeserializers();
            }
            else if(Recipient != null)
            {
                return Recipient.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateMessageRequestBccBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.CreateMessageRequestBccBranch2>(null, CreateMessageRequestBccBranch2);
            }
            else if(Recipient != null)
            {
                writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.Recipient>(null, Recipient);
            }
        }
    }
}
#pragma warning restore CS0618
