// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of credential to store. Defaults to `text`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateAuthTokenRequestTokenType
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "oauth")]
        #pragma warning disable CS1591
        OAuth,
        #pragma warning restore CS1591
    }
}
