// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// You can create a Ticket Type Attribute
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Create_ticket_type_attribute_request : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the attribute allows multiple files to be attached to it (only applicable to file attributes)</summary>
        public bool? AllowMultipleValues { get; set; }
        /// <summary>The data type of the attribute</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request_data_type? DataType { get; set; }
        /// <summary>The description of the attribute presented to the teammate or contact</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A comma delimited list of items for the attribute value (only applicable to list attributes)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ListItems { get; set; }
#nullable restore
#else
        public string ListItems { get; set; }
#endif
        /// <summary>Whether the attribute allows multiple lines of text (only applicable to string attributes)</summary>
        public bool? Multiline { get; set; }
        /// <summary>The name of the ticket type attribute</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Whether the attribute is required to be filled in when teammates are creating the ticket in Inbox.</summary>
        public bool? RequiredToCreate { get; set; }
        /// <summary>Whether the attribute is required to be filled in when contacts are creating the ticket in Messenger.</summary>
        public bool? RequiredToCreateForContacts { get; set; }
        /// <summary>Whether the attribute is visible to teammates when creating a ticket in Inbox.</summary>
        public bool? VisibleOnCreate { get; set; }
        /// <summary>Whether the attribute is visible to contacts when creating a ticket in Messenger.</summary>
        public bool? VisibleToContacts { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request"/> and sets the default values.
        /// </summary>
        public Create_ticket_type_attribute_request()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_multiple_values", n => { AllowMultipleValues = n.GetBoolValue(); } },
                { "data_type", n => { DataType = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request_data_type>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "list_items", n => { ListItems = n.GetStringValue(); } },
                { "multiline", n => { Multiline = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "required_to_create", n => { RequiredToCreate = n.GetBoolValue(); } },
                { "required_to_create_for_contacts", n => { RequiredToCreateForContacts = n.GetBoolValue(); } },
                { "visible_on_create", n => { VisibleOnCreate = n.GetBoolValue(); } },
                { "visible_to_contacts", n => { VisibleToContacts = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_multiple_values", AllowMultipleValues);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.Create_ticket_type_attribute_request_data_type>("data_type", DataType);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("list_items", ListItems);
            writer.WriteBoolValue("multiline", Multiline);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("required_to_create", RequiredToCreate);
            writer.WriteBoolValue("required_to_create_for_contacts", RequiredToCreateForContacts);
            writer.WriteBoolValue("visible_on_create", VisibleOnCreate);
            writer.WriteBoolValue("visible_to_contacts", VisibleToContacts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
