// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of object - `data_connector.execution`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DataConnectorExecutionResultType
    {
        [EnumMember(Value = "data_connector.execution")]
        #pragma warning disable CS1591
        DataConnectorExecution,
        #pragma warning restore CS1591
    }
}
