// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// A paginated list of data connector execution results.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataConnectorExecutionResultList : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of execution result objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResult>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResult> Data { get; set; }
#endif
        /// <summary>Pagination information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultListPages? Pages { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultListPages Pages { get; set; }
#endif
        /// <summary>The type of object - `list`.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList"/> and sets the default values.
        /// </summary>
        public DataConnectorExecutionResultList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResult>(global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pages", n => { Pages = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultListPages>(global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultListPages.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResult>("data", Data);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultListPages>("pages", Pages);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.DataConnectorExecutionResultList_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
