// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DataConnectorDetail_object_mappings_intercom_object_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "conversation")]
        #pragma warning disable CS1591
        Conversation,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
