// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of object which was deleted. - article</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeletedArticleObject_object
    {
        [EnumMember(Value = "article")]
        #pragma warning disable CS1591
        Article,
        #pragma warning restore CS1591
    }
}
