// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// The request payload for updating dynamic content. All fields are optional — only provided fields are updated.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicContentUpdateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The locale whose variation is used when there&apos;s no variation for the requested locale. The dynamic content must have a variation for this locale that applies to all brands.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultLocale { get; set; }
#nullable restore
#else
        public string DefaultLocale { get; set; }
#endif
        /// <summary>The name of the dynamic content. Must be unique in the workspace. Renaming doesn&apos;t change the `key`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The full set of variations. Existing variations that aren&apos;t included are deleted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationRequest>? Variations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationRequest> Variations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentUpdateRequest"/> and sets the default values.
        /// </summary>
        public DynamicContentUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_locale", n => { DefaultLocale = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "variations", n => { Variations = n.GetCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationRequest>(global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationRequest.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("default_locale", DefaultLocale);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationRequest>("variations", Variations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
