// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// The value of a dynamic content for one locale, and optionally one brand.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DynamicContentVariation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier for the brand the variation applies to. `null` for a variation that applies to all brands.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrandId { get; set; }
#nullable restore
#else
        public string BrandId { get; set; }
#endif
        /// <summary>The time the variation was created as a Unix timestamp.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The unique identifier for the variation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the variation is intentionally empty. An intentionally empty variation shows nothing instead of falling back to the default content, and has an empty `text_content` or `json_blocks`.</summary>
        public bool? IntentionallyEmpty { get; set; }
        /// <summary>The content blocks of a block variation. `null` for inline dynamic content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationJsonBlocksItemProperty>? JsonBlocks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationJsonBlocksItemProperty> JsonBlocks { get; set; }
#endif
        /// <summary>The locale of the variation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The value of an inline variation. `null` for block dynamic content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextContent { get; set; }
#nullable restore
#else
        public string TextContent { get; set; }
#endif
        /// <summary>String representing the object&apos;s type. Always has the value `dynamic_content_variation`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The time the variation was last updated as a Unix timestamp.</summary>
        public int? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariation"/> and sets the default values.
        /// </summary>
        public DynamicContentVariation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brand_id", n => { BrandId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "intentionally_empty", n => { IntentionallyEmpty = n.GetBoolValue(); } },
                { "json_blocks", n => { JsonBlocks = n.GetCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationJsonBlocksItemProperty>(global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationJsonBlocksItemProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "text_content", n => { TextContent = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("brand_id", BrandId);
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("intentionally_empty", IntentionallyEmpty);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Intercom.OpenApiClient.Models.DynamicContentVariationJsonBlocksItemProperty>("json_blocks", JsonBlocks);
            writer.WriteStringValue("locale", Locale);
            writer.WriteStringValue("text_content", TextContent);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
