// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The resulting status of the conversation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EscalatedStatus
    {
        [EnumMember(Value = "escalated")]
        #pragma warning disable CS1591
        Escalated,
        #pragma warning restore CS1591
    }
}
