// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>Always en</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ExternalPage_locale
    {
        [EnumMember(Value = "en")]
        #pragma warning disable CS1591
        En,
        #pragma warning restore CS1591
    }
}
