// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// A list of the company ids a contact has been granted access to.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GrantedCompanyList : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The `company_id` values of the companies the contact has been granted access to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CompanyIds { get; set; }
#nullable restore
#else
        public List<string> CompanyIds { get; set; }
#endif
        /// <summary>Pagination details. Null on the replace response, which returns the whole stored set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyListPages? Pages { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyListPages Pages { get; set; }
#endif
        /// <summary>The total number of companies the contact has been granted access to.</summary>
        public int? TotalCount { get; set; }
        /// <summary>The type of the object.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.ListType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyList"/> and sets the default values.
        /// </summary>
        public GrantedCompanyList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company_ids", n => { CompanyIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pages", n => { Pages = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyListPages>(global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyListPages.CreateFromDiscriminatorValue); } },
                { "total_count", n => { TotalCount = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ListType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("company_ids", CompanyIds);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.GrantedCompanyListPages>("pages", Pages);
            writer.WriteIntValue("total_count", TotalCount);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.ListType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
