// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of the redirect target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum HelpCenterRedirectTargetType
    {
        [EnumMember(Value = "article")]
        #pragma warning disable CS1591
        Article,
        #pragma warning restore CS1591
        [EnumMember(Value = "collection")]
        #pragma warning disable CS1591
        Collection,
        #pragma warning restore CS1591
    }
}
