// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// A redirect maps a source URL (`from_url`) to an article or collection within ahelp center, so that links to old or external URLs resolve to live content.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HelpCenterRedirect : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time the redirect was created as a UTC Unix timestamp.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>The source URL that is redirected. An absolute URL within the help center&apos;s URL space.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromUrl { get; set; }
#nullable restore
#else
        public string FromUrl { get; set; }
#endif
        /// <summary>The unique identifier for the help center the redirect belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpCenterId { get; set; }
#nullable restore
#else
        public string HelpCenterId { get; set; }
#endif
        /// <summary>The unique identifier for the redirect.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The locale of the redirect&apos;s target. For article targets this is the bound translation&apos;s locale, which may differ from the requested locale if no translation exists in that locale.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The unique identifier of the target article or collection. For article targets this is the Article ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetId { get; set; }
#nullable restore
#else
        public string TargetId { get; set; }
#endif
        /// <summary>The type of the redirect target.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectTargetType? TargetType { get; set; }
        /// <summary>The type of the object - `help_center_redirect`.</summary>
        public global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectType? Type { get; set; }
        /// <summary>The time the redirect was last updated as a UTC Unix timestamp.</summary>
        public int? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirect"/> and sets the default values.
        /// </summary>
        public HelpCenterRedirect()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirect"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirect CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirect();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "from_url", n => { FromUrl = n.GetStringValue(); } },
                { "help_center_id", n => { HelpCenterId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "target_id", n => { TargetId = n.GetStringValue(); } },
                { "target_type", n => { TargetType = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectTargetType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteStringValue("from_url", FromUrl);
            writer.WriteStringValue("help_center_id", HelpCenterId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("locale", Locale);
            writer.WriteStringValue("target_id", TargetId);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectTargetType>("target_type", TargetType);
            writer.WriteEnumValue<global::Soenneker.Intercom.OpenApiClient.Models.HelpCenterRedirectType>("type", Type);
            writer.WriteIntValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
