// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of pagination</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MacroListPages_type
    {
        [EnumMember(Value = "pages")]
        #pragma warning disable CS1591
        Pages,
        #pragma warning restore CS1591
    }
}
