// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>A stable code identifying the reason. Branch on this value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MergePreviewReasonCode
    {
        [EnumMember(Value = "source_same_as_target")]
        #pragma warning disable CS1591
        SourceSameAsTarget,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_merge_role_pair")]
        #pragma warning disable CS1591
        InvalidMergeRolePair,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_shared_identifier")]
        #pragma warning disable CS1591
        NoSharedIdentifier,
        #pragma warning restore CS1591
        [EnumMember(Value = "facebook_user")]
        #pragma warning disable CS1591
        FacebookUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "external_lead_channel_not_allowed")]
        #pragma warning disable CS1591
        ExternalLeadChannelNotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "mailing_list")]
        #pragma warning disable CS1591
        MailingList,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_to_lead")]
        #pragma warning disable CS1591
        UserToLead,
        #pragma warning restore CS1591
        [EnumMember(Value = "whatsapp_data_cannot_be_merged")]
        #pragma warning disable CS1591
        WhatsappDataCannotBeMerged,
        #pragma warning restore CS1591
        [EnumMember(Value = "telegram_data_cannot_be_merged")]
        #pragma warning disable CS1591
        TelegramDataCannotBeMerged,
        #pragma warning restore CS1591
        [EnumMember(Value = "source_has_telegram_data")]
        #pragma warning disable CS1591
        SourceHasTelegramData,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_data_cannot_be_merged")]
        #pragma warning disable CS1591
        PhoneDataCannotBeMerged,
        #pragma warning restore CS1591
    }
}
