// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>How the value is resolved. adopted = the source&apos;s value is taken; discarded = the source&apos;s value is dropped and the target&apos;s kept; merged = the two values are combined.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MergePreviewAttributeChangeOutcome
    {
        [EnumMember(Value = "adopted")]
        #pragma warning disable CS1591
        Adopted,
        #pragma warning restore CS1591
        [EnumMember(Value = "discarded")]
        #pragma warning disable CS1591
        Discarded,
        #pragma warning restore CS1591
        [EnumMember(Value = "merged")]
        #pragma warning disable CS1591
        Merged,
        #pragma warning restore CS1591
    }
}
