// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>An operator to allow boolean inspection between multiple fields.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MultipleFilterSearchRequestOperator
    {
        [EnumMember(Value = "AND")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
        [EnumMember(Value = "OR")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
    }
}
