// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Post_export_reporting_data_enqueue : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of attribute identifiers to include in the export. Requires qualified_id format (e.g., &quot;people.Brand&quot;, &quot;standard.conversation_id&quot;). Use the qualified_id returned from the get_datasets response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AttributeIds { get; set; }
#nullable restore
#else
        public List<string> AttributeIds { get; set; }
#endif
        /// <summary>The dataset_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatasetId { get; set; }
#nullable restore
#else
        public string DatasetId { get; set; }
#endif
        /// <summary>The end_time property</summary>
        public long? EndTime { get; set; }
        /// <summary>The start_time property</summary>
        public long? StartTime { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Post_export_reporting_data_enqueue"/> and sets the default values.
        /// </summary>
        public Post_export_reporting_data_enqueue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.Post_export_reporting_data_enqueue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.Post_export_reporting_data_enqueue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.Post_export_reporting_data_enqueue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attribute_ids", n => { AttributeIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "dataset_id", n => { DatasetId = n.GetStringValue(); } },
                { "end_time", n => { EndTime = n.GetLongValue(); } },
                { "start_time", n => { StartTime = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("attribute_ids", AttributeIds);
            writer.WriteStringValue("dataset_id", DatasetId);
            writer.WriteLongValue("end_time", EndTime);
            writer.WriteLongValue("start_time", StartTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
