// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of resource being redacted.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Redact_conversation_requestMember1_type
    {
        [EnumMember(Value = "conversation_part")]
        #pragma warning disable CS1591
        Conversation_part,
        #pragma warning restore CS1591
    }
}
