// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchContentTagOperatorParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IN")]
        #pragma warning disable CS1591
        InValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "NIN")]
        #pragma warning disable CS1591
        Nin,
        #pragma warning restore CS1591
    }
}
