// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>Describes the type of consent.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Subscription_type_consent_type
    {
        [EnumMember(Value = "opt_out")]
        #pragma warning disable CS1591
        Opt_out,
        #pragma warning restore CS1591
        [EnumMember(Value = "opt_in")]
        #pragma warning disable CS1591
        Opt_in,
        #pragma warning restore CS1591
    }
}
