// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>always contact.list</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TicketContacts_type
    {
        [EnumMember(Value = "contact.list")]
        #pragma warning disable CS1591
        ContactList,
        #pragma warning restore CS1591
    }
}
