// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>Always ticket</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TicketTypeEnum
    {
        [EnumMember(Value = "ticket")]
        #pragma warning disable CS1591
        Ticket,
        #pragma warning restore CS1591
    }
}
