// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>Type of the part</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ticket_reply_part_type
    {
        [EnumMember(Value = "note")]
        #pragma warning disable CS1591
        Note,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment")]
        #pragma warning disable CS1591
        Comment,
        #pragma warning restore CS1591
        [EnumMember(Value = "quick_reply")]
        #pragma warning disable CS1591
        Quick_reply,
        #pragma warning restore CS1591
    }
}
