// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of the object. Always &apos;value&apos;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TicketPart_updated_attribute_data_value_type
    {
        [EnumMember(Value = "value")]
        #pragma warning disable CS1591
        Value,
        #pragma warning restore CS1591
    }
}
