// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>
    /// The request payload for updating a team&apos;s membership.`admin_ids` is the complete set of teammates who should be on the team oncethe request completes, not a list of changes to apply. Any teammate currentlyon the team but absent from `admin_ids` is removed.The team&apos;s members and their priority levels are the only parts of a team thisendpoint writes, and the request is read from the body: a parameter sent in thequery string is rejected rather than applied. A team read from the API can be sentback whole, since the other fields of the representation are accepted as long asthey are unchanged. Trying to change one of them returns a 400 rather than beingignored, as does any field a team does not have.`admin_priority_level` sets which teammates take work first. It is optional, andnames only the teammates whose level the request is setting: a teammate it leavesout keeps the level they already have, and one joining the team without a levelnamed becomes a primary member. A level named for a teammate the request removes isignored, so a team read from the API can still be sent back whole with only`admin_ids` changed.Naming an id that is on neither the team nor `admin_ids` returns a 400. So doesnaming the same id at both levels, unless the team really does hold that teammateat both: a read reports that shape, and sending it back settles them at a singlelevel rather than being refused.Only a team whose `distribution_method` is `load_balanced` can have secondarymembers, so `secondary_admin_ids` returns a 400 on any other team.`primary_admin_ids` is accepted on every team, but a team that does not balanceassignment does not report `admin_priority_level` back and does not use the levelsto decide who work goes to.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateTeamMembersRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ids of every teammate who should be a member of the team. Must contain at least one id, and no more than 1000.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AdminIds { get; set; }
#nullable restore
#else
        public List<int?> AdminIds { get; set; }
#endif
        /// <summary>The priority levels to set, naming only the teammates whose level is being set</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Intercom.OpenApiClient.Models.AdminPriorityLevelRequest? AdminPriorityLevel { get; set; }
#nullable restore
#else
        public global::Soenneker.Intercom.OpenApiClient.Models.AdminPriorityLevelRequest AdminPriorityLevel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Intercom.OpenApiClient.Models.UpdateTeamMembersRequest"/> and sets the default values.
        /// </summary>
        public UpdateTeamMembersRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Intercom.OpenApiClient.Models.UpdateTeamMembersRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Intercom.OpenApiClient.Models.UpdateTeamMembersRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Intercom.OpenApiClient.Models.UpdateTeamMembersRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admin_ids", n => { AdminIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "admin_priority_level", n => { AdminPriorityLevel = n.GetObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.AdminPriorityLevelRequest>(global::Soenneker.Intercom.OpenApiClient.Models.AdminPriorityLevelRequest.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("admin_ids", AdminIds);
            writer.WriteObjectValue<global::Soenneker.Intercom.OpenApiClient.Models.AdminPriorityLevelRequest>("admin_priority_level", AdminPriorityLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
