// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Intercom.OpenApiClient.Models
{
    /// <summary>The type of the object</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VisitorTagsTagsItemType
    {
        [EnumMember(Value = "tag")]
        #pragma warning disable CS1591
        Tag,
        #pragma warning restore CS1591
    }
}
